# Generated by Django 6.0.4 on 2026-05-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quantify', models.IntegerField()),
                ('image', models.CharField(max_length=2083)),
                ('description', models.TextField(blank=True, null=True)),
                ('specialist', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
