# Generated by Django 6.0.4 on 2026-05-16 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (0, 'Domingo')], unique=True)),
                ('hora_inicio', models.TimeField(help_text='Hora de apertura del Spa')),
                ('hora_fin', models.TimeField(help_text='Hora de cierre del Spa')),
            ],
            options={
                'verbose_name': 'Horario de Trabajo',
                'verbose_name_plural': 'Horarios de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Specialist',
                'verbose_name_plural': 'Specialists',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quantify', models.IntegerField()),
                ('image', models.CharField(max_length=2083)),
                ('categoria', models.CharField(choices=[('FACIAL', 'Faciales'), ('CORPORAL', 'Corporales')], default='FACIAL', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('specialist', models.CharField(blank=True, max_length=255, null=True)),
                ('specialists', models.ManyToManyField(blank=True, related_name='services', to='coffee.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'En revisión'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.servicio')),
                ('especialista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coffee.specialist')),
            ],
        ),
    ]
