# Generated by Django 6.0.4 on 2026-05-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('FACIAL', 'Faciales'), ('CORPORAL', 'Corporales')], default='FACIAL', max_length=20),
        ),
    ]
