# Generated by Django 6.0.4 on 2026-06-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'En revisión'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20),
        ),
    ]
