# Generated by Django 6.0.6 on 2026-06-05 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='specialist_response',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='specialist_token',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name='specialist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
