# Generated by Django 6.0.6 on 2026-06-05 03:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_reserva_specialist_response_reserva_specialist_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='specialist_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
