# Generated by Django 6.0.6 on 2026-06-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_alter_reserva_specialist_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='photo',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
