# Generated by Django 6.0.6 on 2026-06-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_specialist_bio_specialist_phone_specialist_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='photo',
        ),
        migrations.AddField(
            model_name='specialist',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
