# Generated by Django 6.0.6 on 2026-06-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_remove_specialist_bio_remove_specialist_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='last_name',
        ),
    ]
